spring:
  application:
    name: mercado-livro
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivro
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver