spring:
  application:
    name: mercado-livro
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadolivro
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: non-null

jwt:
  secret: 90a4187b-8b6b-4f35-859e-b640d2e4dc88
  expiration: 999999